version: "3"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt:v0.3.1
    # build: ../
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    profiles: ["exclude-from-up"]
    volumes:
      - ./volumes/auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./volumes/data:/app/data
      ## allow auto-gpt to write logs to disk
      - ./volumes/logs:/app/logs
      ## uncomment following lines if you have / want to make use of these files
      #- ./azure.yaml:/app/azure.yaml
      #- ./ai_settings.yaml:/app/ai_settings.yaml

  redis:
    image: redis/redis-stack-server:latest
